	drop table if exists member CASCADE

	create table comment
    (
        id   bigint generated by default as identity,
        name varchar(255),
        content varchar(1024),
        date varchar(255),
        password varchar(255),
        primary key (id)
    );